# Generated by Django 3.0.5 on 2020-05-01 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugbook', '0003_comments_bug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppDetails',
            new_name='AppDetail',
        ),
        migrations.RenameModel(
            old_name='BugDetails',
            new_name='BugDetail',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
