# Generated by Django 3.0.5 on 2020-05-01 06:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugbook', '0004_auto_20200501_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='wiki',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
