# Generated by Django 3.0.5 on 2020-05-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugbook', '0005_auto_20200501_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='creator',
        ),
    ]
