# Generated by Django 3.0.5 on 2020-06-03 07:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbook', '0006_auto_20200505_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugdetail',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='bugdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Resolved'), ('w', 'Working'), ('ns', 'Not Seen')], default='Not Seen', max_length=2),
        ),
    ]
