# Generated by Django 3.0.5 on 2020-06-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugbook', '0007_auto_20200603_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugbook.BugDetail'),
        ),
    ]
